
CREATE TABLE notice (

    id              integer generated by default as identity,
    message         varchar(255),
    type            varchar(255),
    processed       boolean,
    primary key (id)
)